# Generated by Django 5.2 on 2025-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hens', models.PositiveIntegerField()),
                ('eggs', models.PositiveIntegerField()),
                ('egg_count', models.IntegerField(help_text='In kilograms')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
