# Generated by Django 5.2 on 2025-05-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myRecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chickenrecord',
            old_name='egg_count',
            new_name='feed',
        ),
    ]
