# Generated by Django 5.2 on 2025-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myRecords', '0002_rename_egg_count_chickenrecord_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cows', models.PositiveIntegerField()),
                ('milk', models.IntegerField(help_text='In liters')),
                ('feed', models.IntegerField(help_text='In kilograms')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
